version: 2
jobs:
  backend:
    working_directory: ~/birdie-test/backend
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies - backend
          command: |
            cd backend/ && npm install
      - run:
          name: Run tests - backend
          command: |
            cd backend/ && npm test
  frontend:
    working_directory: ~/birdie-test/frontend
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies - frontend
          command: |
            cd frontend/ && npm install
      - run:
          name: Install react scripts - frontend
          command: |
            cd frontend/ && sudo npm install react-scripts@3.0.1 -g
      - run:
          name: Run snapshot tests - frontend
          command: |
            cd frontend/ && npm test

workflows:
  version: 2
  backend_and_frontend:
    jobs:
      - backend
      - frontend